# Generated by Django 4.2.2 on 2023-06-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_addcar_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='car_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
