# Generated by Django 4.2.2 on 2023-06-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_addcar_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcar',
            old_name='car_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='addcar',
            old_name='car_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='addcar',
            old_name='car_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='addcar',
            old_name='car_price',
            new_name='price',
        ),
    ]
