# Generated by Django 4.2.2 on 2023-06-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_car_description_addcar_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
