# Generated by Django 4.2.2 on 2023-06-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_addcar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcar',
            name='transmition',
            field=models.CharField(default='Manual', max_length=100),
        ),
    ]
